### ISSUE TITLE
this code can't run

### ISSUE THREAD

**Issue by FlorinAndrei** [PlatorSolutions/quarterly-earnings-machine-learning-algo#2]
https://github.com/PlatorSolutions/quarterly-earnings-machine-learning-algo/blob/master/cloudml_prepare_local_csv.py

Line 30 is bound to fail:

```
df['prc_change_t2'] = pd.qcut(df.prc_change, q=5, labels=range(5))
```

On line 12, you drop all columns except `prc_change_t2` and `filename`:

```
financials = financials[['prc_change_t2', 'filename']].set_index('filename')
```

On line 14, you create a new dataframe with two columns:

```
df = pd.DataFrame(columns=['text', 'filename'])
```

On line 28 you join them:

```
df = df.join(financials)
```

What you have between lines 28 and 30 is a dataframe with `filename` as an index, and the columns are `text` and `prc_change_t2`. There's no column called `prc_change` in the dataframe there.

**Comment by Ben-Sherman** [comment]
Fixed https://github.com/PlatorSolutions/quarterly-earnings-machine-learning-algo/commit/4ce8e1e829ed6f6ecd74f8abbfaf91114af1201b
